//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastorNetTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchGroup
    {
        public BranchGroup()
        {
            this.BranchGroupElement = new HashSet<BranchGroupElement>();
        }
    
        public int BranchGroupId { get; set; }
        public string BranchGroupName { get; set; }
        public Nullable<int> ParentBranchGroupId { get; set; }
    
        public virtual ICollection<BranchGroupElement> BranchGroupElement { get; set; }
    }
}
