//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastorNetTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.BranchElement = new HashSet<BranchElement>();
            this.RideStop = new HashSet<RideStop>();
        }
    
        public int NodeId { get; set; }
        public string NodeCode { get; set; }
        public string NodeShortNameEn { get; set; }
        public string NodeShortNameAr { get; set; }
        public string NodeLongNameEn { get; set; }
        public string NodeLongNameAr { get; set; }
    
        public virtual ICollection<BranchElement> BranchElement { get; set; }
        public virtual ICollection<RideStop> RideStop { get; set; }
    }
}
