//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastorNetTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ride
    {
        public int OperatorId { get; set; }
        public int RideId { get; set; }
        public string RideCode { get; set; }
        public Nullable<int> RideNumber { get; set; }
        public Nullable<int> RideTypeId { get; set; }
        public string RideName { get; set; }
        public Nullable<int> RideCategory { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> BranchGroupId { get; set; }
        public Nullable<System.DateTime> RideStartDate { get; set; }
        public Nullable<System.DateTime> RideEndDate { get; set; }
        public Nullable<int> DepNodeId { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public Nullable<int> ArrNodeId { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
    }
}
