
U.dll : U.cs U_CommandProcessor.cs U_CsStreamWriter.cs U_Enum.cs U_Lexer.cs U_LLParserLexerLib.cs U_Num.cs U_Tuple.cs
	gmcs -t:library -o:U.dll U.cs U_CommandProcessor.cs U_CsStreamWriter.cs U_Enum.cs U_Lexer.cs U_LLParserLexerLib.cs U_Num.cs U_Tuple.cs

clean :
	rm U.dll
